
version: 2.1


jobs:
  testmtk:
    docker:
      - image: paldier/swrt-docker:latest
        environment:
          PROJECT_DIR: "/home/docker/project"
          TERM: "xterm-256color"
    resource_class: large
    steps:
      - attach_workspace:
          at: .
      - run:
          name: build mtk
          shell: /bin/bash
          command: |
            git clone https://github.com/SWRT-dev/swrt-gpl mtk
            cd mtk/release/src-mtk-arm
            ~/.profile
            sudo /home/docker/envs/toolchain.sh
            make swrt-rm-ax6000
  testqca:
    docker:
      - image: paldier/swrt-docker:latest
        environment:
          PROJECT_DIR: "/home/docker/project"
          TERM: "xterm-256color"
    resource_class: large
    steps:
      - attach_workspace:
          at: .
      - run:
          name: build qca
          shell: /bin/bash
          command: |
            git clone https://github.com/SWRT-dev/swrt-gpl qca
            cd qca/release/src-qca-ipq40xx
            ~/.profile
            sudo /home/docker/envs/toolchain.sh
            make rt-ac82u

workflows:
  build-workflow:
    jobs:
      - testmtk
      - testqca


